---
# tasks file for rdiff-backup-script

- name: Create rdiff-backups folder
  file:
    path: /opt/rdiff-backups
    state: directory
    mode: 0755
  run_once: true
  delegate_to: "{{ rdiff_backup_server }}"
  become: true

- name: Create backup script from template
  template:
    src: backups.sh.j2
    dest: /opt/rdiff-backups/backups.sh
    mode: 0755
  run_once: true
  delegate_to: "{{ rdiff_backup_server }}"
  become: true




